package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Afiliado generated by hbm2java
 */
public class Afiliado implements java.io.Serializable {

	private int idafiliado;
	private ValorAfiliacion valorAfiliacion;
	private String numAfiliacion;
	private String nombreInstitucion;
	private int periodoAfiliacion;
	private Float valorBase;
	private Float valorNegociado;
	private String urlLogo;
	private String estado;
	private String ruc;
	private String nombreContacto;
	private String emailContacto;
	private String celContacto;
	private Set usuarioAfiliados = new HashSet(0);
	private Set valoracionPlans = new HashSet(0);
	private Set eventos = new HashSet(0);
	private Set planestudios = new HashSet(0);
	private Set gestionAcademicas = new HashSet(0);
	private Set promocions = new HashSet(0);
	private Set redAfiliados = new HashSet(0);

	public Afiliado() {
	}

	public Afiliado(int idafiliado, ValorAfiliacion valorAfiliacion, String numAfiliacion, String nombreInstitucion,
			int periodoAfiliacion) {
		this.idafiliado = idafiliado;
		this.valorAfiliacion = valorAfiliacion;
		this.numAfiliacion = numAfiliacion;
		this.nombreInstitucion = nombreInstitucion;
		this.periodoAfiliacion = periodoAfiliacion;
	}

	public Afiliado(int idafiliado, ValorAfiliacion valorAfiliacion, String numAfiliacion, String nombreInstitucion,
			int periodoAfiliacion, Float valorBase, Float valorNegociado, String urlLogo, String estado, String ruc,
			String nombreContacto, String emailContacto, String celContacto, Set usuarioAfiliados, Set valoracionPlans,
			Set eventos, Set planestudios, Set gestionAcademicas, Set promocions, Set redAfiliados) {
		this.idafiliado = idafiliado;
		this.valorAfiliacion = valorAfiliacion;
		this.numAfiliacion = numAfiliacion;
		this.nombreInstitucion = nombreInstitucion;
		this.periodoAfiliacion = periodoAfiliacion;
		this.valorBase = valorBase;
		this.valorNegociado = valorNegociado;
		this.urlLogo = urlLogo;
		this.estado = estado;
		this.ruc = ruc;
		this.nombreContacto = nombreContacto;
		this.emailContacto = emailContacto;
		this.celContacto = celContacto;
		this.usuarioAfiliados = usuarioAfiliados;
		this.valoracionPlans = valoracionPlans;
		this.eventos = eventos;
		this.planestudios = planestudios;
		this.gestionAcademicas = gestionAcademicas;
		this.promocions = promocions;
		this.redAfiliados = redAfiliados;
	}

	public int getIdafiliado() {
		return this.idafiliado;
	}

	public void setIdafiliado(int idafiliado) {
		this.idafiliado = idafiliado;
	}

	public ValorAfiliacion getValorAfiliacion() {
		return this.valorAfiliacion;
	}

	public void setValorAfiliacion(ValorAfiliacion valorAfiliacion) {
		this.valorAfiliacion = valorAfiliacion;
	}

	public String getNumAfiliacion() {
		return this.numAfiliacion;
	}

	public void setNumAfiliacion(String numAfiliacion) {
		this.numAfiliacion = numAfiliacion;
	}

	public String getNombreInstitucion() {
		return this.nombreInstitucion;
	}

	public void setNombreInstitucion(String nombreInstitucion) {
		this.nombreInstitucion = nombreInstitucion;
	}

	public int getPeriodoAfiliacion() {
		return this.periodoAfiliacion;
	}

	public void setPeriodoAfiliacion(int periodoAfiliacion) {
		this.periodoAfiliacion = periodoAfiliacion;
	}

	public Float getValorBase() {
		return this.valorBase;
	}

	public void setValorBase(Float valorBase) {
		this.valorBase = valorBase;
	}

	public Float getValorNegociado() {
		return this.valorNegociado;
	}

	public void setValorNegociado(Float valorNegociado) {
		this.valorNegociado = valorNegociado;
	}

	public String getUrlLogo() {
		return this.urlLogo;
	}

	public void setUrlLogo(String urlLogo) {
		this.urlLogo = urlLogo;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	public String getNombreContacto() {
		return this.nombreContacto;
	}

	public void setNombreContacto(String nombreContacto) {
		this.nombreContacto = nombreContacto;
	}

	public String getEmailContacto() {
		return this.emailContacto;
	}

	public void setEmailContacto(String emailContacto) {
		this.emailContacto = emailContacto;
	}

	public String getCelContacto() {
		return this.celContacto;
	}

	public void setCelContacto(String celContacto) {
		this.celContacto = celContacto;
	}

	public Set getUsuarioAfiliados() {
		return this.usuarioAfiliados;
	}

	public void setUsuarioAfiliados(Set usuarioAfiliados) {
		this.usuarioAfiliados = usuarioAfiliados;
	}

	public Set getValoracionPlans() {
		return this.valoracionPlans;
	}

	public void setValoracionPlans(Set valoracionPlans) {
		this.valoracionPlans = valoracionPlans;
	}

	public Set getEventos() {
		return this.eventos;
	}

	public void setEventos(Set eventos) {
		this.eventos = eventos;
	}

	public Set getPlanestudios() {
		return this.planestudios;
	}

	public void setPlanestudios(Set planestudios) {
		this.planestudios = planestudios;
	}

	public Set getGestionAcademicas() {
		return this.gestionAcademicas;
	}

	public void setGestionAcademicas(Set gestionAcademicas) {
		this.gestionAcademicas = gestionAcademicas;
	}

	public Set getPromocions() {
		return this.promocions;
	}

	public void setPromocions(Set promocions) {
		this.promocions = promocions;
	}

	public Set getRedAfiliados() {
		return this.redAfiliados;
	}

	public void setRedAfiliados(Set redAfiliados) {
		this.redAfiliados = redAfiliados;
	}

}
