package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

/**
 * Articulo generated by hbm2java
 */
public class Articulo implements java.io.Serializable {

	private int idarticulo;
	private ArticuloCategoria articuloCategoria;
	private Usuario usuario;
	private String nombre;
	private String descripcion;
	private Float precio;
	private String urlFoto;
	private String condicionArticulo;

	public Articulo() {
	}

	public Articulo(int idarticulo) {
		this.idarticulo = idarticulo;
	}

	public Articulo(int idarticulo, ArticuloCategoria articuloCategoria, Usuario usuario, String nombre,
			String descripcion, Float precio, String urlFoto, String condicionArticulo) {
		this.idarticulo = idarticulo;
		this.articuloCategoria = articuloCategoria;
		this.usuario = usuario;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.precio = precio;
		this.urlFoto = urlFoto;
		this.condicionArticulo = condicionArticulo;
	}

	public int getIdarticulo() {
		return this.idarticulo;
	}

	public void setIdarticulo(int idarticulo) {
		this.idarticulo = idarticulo;
	}

	public ArticuloCategoria getArticuloCategoria() {
		return this.articuloCategoria;
	}

	public void setArticuloCategoria(ArticuloCategoria articuloCategoria) {
		this.articuloCategoria = articuloCategoria;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	public String getUrlFoto() {
		return this.urlFoto;
	}

	public void setUrlFoto(String urlFoto) {
		this.urlFoto = urlFoto;
	}

	public String getCondicionArticulo() {
		return this.condicionArticulo;
	}

	public void setCondicionArticulo(String condicionArticulo) {
		this.condicionArticulo = condicionArticulo;
	}

}
