package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ArticuloCategoria generated by hbm2java
 */
public class ArticuloCategoria implements java.io.Serializable {

	private int idarticulocategoria;
	private String categoria;
	private Set articulos = new HashSet(0);

	public ArticuloCategoria() {
	}

	public ArticuloCategoria(int idarticulocategoria, String categoria) {
		this.idarticulocategoria = idarticulocategoria;
		this.categoria = categoria;
	}

	public ArticuloCategoria(int idarticulocategoria, String categoria, Set articulos) {
		this.idarticulocategoria = idarticulocategoria;
		this.categoria = categoria;
		this.articulos = articulos;
	}

	public int getIdarticulocategoria() {
		return this.idarticulocategoria;
	}

	public void setIdarticulocategoria(int idarticulocategoria) {
		this.idarticulocategoria = idarticulocategoria;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public Set getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Set articulos) {
		this.articulos = articulos;
	}

}
