package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera implements java.io.Serializable {

	private int idcarrera;
	private String nombreCarrera;
	private Set solicitudMentors = new HashSet(0);
	private Set planestudios = new HashSet(0);
	private Set solicitudMentorias = new HashSet(0);

	public Carrera() {
	}

	public Carrera(int idcarrera) {
		this.idcarrera = idcarrera;
	}

	public Carrera(int idcarrera, String nombreCarrera, Set solicitudMentors, Set planestudios,
			Set solicitudMentorias) {
		this.idcarrera = idcarrera;
		this.nombreCarrera = nombreCarrera;
		this.solicitudMentors = solicitudMentors;
		this.planestudios = planestudios;
		this.solicitudMentorias = solicitudMentorias;
	}

	public int getIdcarrera() {
		return this.idcarrera;
	}

	public void setIdcarrera(int idcarrera) {
		this.idcarrera = idcarrera;
	}

	public String getNombreCarrera() {
		return this.nombreCarrera;
	}

	public void setNombreCarrera(String nombreCarrera) {
		this.nombreCarrera = nombreCarrera;
	}

	public Set getSolicitudMentors() {
		return this.solicitudMentors;
	}

	public void setSolicitudMentors(Set solicitudMentors) {
		this.solicitudMentors = solicitudMentors;
	}

	public Set getPlanestudios() {
		return this.planestudios;
	}

	public void setPlanestudios(Set planestudios) {
		this.planestudios = planestudios;
	}

	public Set getSolicitudMentorias() {
		return this.solicitudMentorias;
	}

	public void setSolicitudMentorias(Set solicitudMentorias) {
		this.solicitudMentorias = solicitudMentorias;
	}

}
