package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

/**
 * EvaluacionMentoriado generated by hbm2java
 */
public class EvaluacionMentoriado implements java.io.Serializable {

	private int idevaluacionmentoriado;
	private Usuario usuarioByIdUsuarioMentoriado;
	private Usuario usuarioByIdUsuarioMentor;
	private Integer valoracion;
	private String comentarios;

	public EvaluacionMentoriado() {
	}

	public EvaluacionMentoriado(int idevaluacionmentoriado, Usuario usuarioByIdUsuarioMentoriado,
			Usuario usuarioByIdUsuarioMentor) {
		this.idevaluacionmentoriado = idevaluacionmentoriado;
		this.usuarioByIdUsuarioMentoriado = usuarioByIdUsuarioMentoriado;
		this.usuarioByIdUsuarioMentor = usuarioByIdUsuarioMentor;
	}

	public EvaluacionMentoriado(int idevaluacionmentoriado, Usuario usuarioByIdUsuarioMentoriado,
			Usuario usuarioByIdUsuarioMentor, Integer valoracion, String comentarios) {
		this.idevaluacionmentoriado = idevaluacionmentoriado;
		this.usuarioByIdUsuarioMentoriado = usuarioByIdUsuarioMentoriado;
		this.usuarioByIdUsuarioMentor = usuarioByIdUsuarioMentor;
		this.valoracion = valoracion;
		this.comentarios = comentarios;
	}

	public int getIdevaluacionmentoriado() {
		return this.idevaluacionmentoriado;
	}

	public void setIdevaluacionmentoriado(int idevaluacionmentoriado) {
		this.idevaluacionmentoriado = idevaluacionmentoriado;
	}

	public Usuario getUsuarioByIdUsuarioMentoriado() {
		return this.usuarioByIdUsuarioMentoriado;
	}

	public void setUsuarioByIdUsuarioMentoriado(Usuario usuarioByIdUsuarioMentoriado) {
		this.usuarioByIdUsuarioMentoriado = usuarioByIdUsuarioMentoriado;
	}

	public Usuario getUsuarioByIdUsuarioMentor() {
		return this.usuarioByIdUsuarioMentor;
	}

	public void setUsuarioByIdUsuarioMentor(Usuario usuarioByIdUsuarioMentor) {
		this.usuarioByIdUsuarioMentor = usuarioByIdUsuarioMentor;
	}

	public Integer getValoracion() {
		return this.valoracion;
	}

	public void setValoracion(Integer valoracion) {
		this.valoracion = valoracion;
	}

	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

}
