package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * EvaluacionMentor generated by hbm2java
 */
public class EvaluacionMentor implements java.io.Serializable {

	private int idevaluacionmentor;
	private Usuario usuarioByIdUsuarioMentor;
	private Usuario usuarioByIdUsuarioEvaluador;
	private Integer valoracion;
	private Date fecha;
	private String comentario;

	public EvaluacionMentor() {
	}

	public EvaluacionMentor(int idevaluacionmentor, Usuario usuarioByIdUsuarioMentor,
			Usuario usuarioByIdUsuarioEvaluador) {
		this.idevaluacionmentor = idevaluacionmentor;
		this.usuarioByIdUsuarioMentor = usuarioByIdUsuarioMentor;
		this.usuarioByIdUsuarioEvaluador = usuarioByIdUsuarioEvaluador;
	}

	public EvaluacionMentor(int idevaluacionmentor, Usuario usuarioByIdUsuarioMentor,
			Usuario usuarioByIdUsuarioEvaluador, Integer valoracion, Date fecha, String comentario) {
		this.idevaluacionmentor = idevaluacionmentor;
		this.usuarioByIdUsuarioMentor = usuarioByIdUsuarioMentor;
		this.usuarioByIdUsuarioEvaluador = usuarioByIdUsuarioEvaluador;
		this.valoracion = valoracion;
		this.fecha = fecha;
		this.comentario = comentario;
	}

	public int getIdevaluacionmentor() {
		return this.idevaluacionmentor;
	}

	public void setIdevaluacionmentor(int idevaluacionmentor) {
		this.idevaluacionmentor = idevaluacionmentor;
	}

	public Usuario getUsuarioByIdUsuarioMentor() {
		return this.usuarioByIdUsuarioMentor;
	}

	public void setUsuarioByIdUsuarioMentor(Usuario usuarioByIdUsuarioMentor) {
		this.usuarioByIdUsuarioMentor = usuarioByIdUsuarioMentor;
	}

	public Usuario getUsuarioByIdUsuarioEvaluador() {
		return this.usuarioByIdUsuarioEvaluador;
	}

	public void setUsuarioByIdUsuarioEvaluador(Usuario usuarioByIdUsuarioEvaluador) {
		this.usuarioByIdUsuarioEvaluador = usuarioByIdUsuarioEvaluador;
	}

	public Integer getValoracion() {
		return this.valoracion;
	}

	public void setValoracion(Integer valoracion) {
		this.valoracion = valoracion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

}
