package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Evento generated by hbm2java
 */
public class Evento implements java.io.Serializable {

	private int idevento;
	private Afiliado afiliado;
	private String local;
	private Date fecha;
	private String direccion;
	private Date horaInicial;
	private Date horaFinal;
	private String descripcion;
	private String urlFoto;
	private Integer estado;

	public Evento() {
	}

	public Evento(int idevento, Afiliado afiliado) {
		this.idevento = idevento;
		this.afiliado = afiliado;
	}

	public Evento(int idevento, Afiliado afiliado, String local, Date fecha, String direccion, Date horaInicial,
			Date horaFinal, String descripcion, String urlFoto, Integer estado) {
		this.idevento = idevento;
		this.afiliado = afiliado;
		this.local = local;
		this.fecha = fecha;
		this.direccion = direccion;
		this.horaInicial = horaInicial;
		this.horaFinal = horaFinal;
		this.descripcion = descripcion;
		this.urlFoto = urlFoto;
		this.estado = estado;
	}

	public int getIdevento() {
		return this.idevento;
	}

	public void setIdevento(int idevento) {
		this.idevento = idevento;
	}

	public Afiliado getAfiliado() {
		return this.afiliado;
	}

	public void setAfiliado(Afiliado afiliado) {
		this.afiliado = afiliado;
	}

	public String getLocal() {
		return this.local;
	}

	public void setLocal(String local) {
		this.local = local;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Date getHoraInicial() {
		return this.horaInicial;
	}

	public void setHoraInicial(Date horaInicial) {
		this.horaInicial = horaInicial;
	}

	public Date getHoraFinal() {
		return this.horaFinal;
	}

	public void setHoraFinal(Date horaFinal) {
		this.horaFinal = horaFinal;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getUrlFoto() {
		return this.urlFoto;
	}

	public void setUrlFoto(String urlFoto) {
		this.urlFoto = urlFoto;
	}

	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

}
