package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * ForoMentoriaDetalle generated by hbm2java
 */
public class ForoMentoriaDetalle implements java.io.Serializable {

	private int idforomentoriadetalle;
	private Usuario usuario;
	private Date fecha;
	private String estado;
	private String contenido;
	private String urlArchivo;

	public ForoMentoriaDetalle() {
	}

	public ForoMentoriaDetalle(int idforomentoriadetalle, Usuario usuario) {
		this.idforomentoriadetalle = idforomentoriadetalle;
		this.usuario = usuario;
	}

	public ForoMentoriaDetalle(int idforomentoriadetalle, Usuario usuario, Date fecha, String estado, String contenido,
			String urlArchivo) {
		this.idforomentoriadetalle = idforomentoriadetalle;
		this.usuario = usuario;
		this.fecha = fecha;
		this.estado = estado;
		this.contenido = contenido;
		this.urlArchivo = urlArchivo;
	}

	public int getIdforomentoriadetalle() {
		return this.idforomentoriadetalle;
	}

	public void setIdforomentoriadetalle(int idforomentoriadetalle) {
		this.idforomentoriadetalle = idforomentoriadetalle;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	public String getUrlArchivo() {
		return this.urlArchivo;
	}

	public void setUrlArchivo(String urlArchivo) {
		this.urlArchivo = urlArchivo;
	}

}
