package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * ForoMentoria generated by hbm2java
 */
public class ForoMentoria implements java.io.Serializable {

	private int idforomentoria;
	private Usuario usuarioByIdUsuarioMentor;
	private Usuario usuarioByIdUsuario;
	private String nombreForo;
	private Date fecha;
	private String estado;

	public ForoMentoria() {
	}

	public ForoMentoria(int idforomentoria, Usuario usuarioByIdUsuarioMentor, Usuario usuarioByIdUsuario) {
		this.idforomentoria = idforomentoria;
		this.usuarioByIdUsuarioMentor = usuarioByIdUsuarioMentor;
		this.usuarioByIdUsuario = usuarioByIdUsuario;
	}

	public ForoMentoria(int idforomentoria, Usuario usuarioByIdUsuarioMentor, Usuario usuarioByIdUsuario,
			String nombreForo, Date fecha, String estado) {
		this.idforomentoria = idforomentoria;
		this.usuarioByIdUsuarioMentor = usuarioByIdUsuarioMentor;
		this.usuarioByIdUsuario = usuarioByIdUsuario;
		this.nombreForo = nombreForo;
		this.fecha = fecha;
		this.estado = estado;
	}

	public int getIdforomentoria() {
		return this.idforomentoria;
	}

	public void setIdforomentoria(int idforomentoria) {
		this.idforomentoria = idforomentoria;
	}

	public Usuario getUsuarioByIdUsuarioMentor() {
		return this.usuarioByIdUsuarioMentor;
	}

	public void setUsuarioByIdUsuarioMentor(Usuario usuarioByIdUsuarioMentor) {
		this.usuarioByIdUsuarioMentor = usuarioByIdUsuarioMentor;
	}

	public Usuario getUsuarioByIdUsuario() {
		return this.usuarioByIdUsuario;
	}

	public void setUsuarioByIdUsuario(Usuario usuarioByIdUsuario) {
		this.usuarioByIdUsuario = usuarioByIdUsuario;
	}

	public String getNombreForo() {
		return this.nombreForo;
	}

	public void setNombreForo(String nombreForo) {
		this.nombreForo = nombreForo;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
