package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * FotoPublicoDetalle generated by hbm2java
 */
public class FotoPublicoDetalle implements java.io.Serializable {

	private int idfotoPublicoDetalle;
	private Usuario usuario;
	private Date fecha;
	private String contenido;
	private String urlArchivo;
	private String estado;

	public FotoPublicoDetalle() {
	}

	public FotoPublicoDetalle(int idfotoPublicoDetalle, Usuario usuario) {
		this.idfotoPublicoDetalle = idfotoPublicoDetalle;
		this.usuario = usuario;
	}

	public FotoPublicoDetalle(int idfotoPublicoDetalle, Usuario usuario, Date fecha, String contenido,
			String urlArchivo, String estado) {
		this.idfotoPublicoDetalle = idfotoPublicoDetalle;
		this.usuario = usuario;
		this.fecha = fecha;
		this.contenido = contenido;
		this.urlArchivo = urlArchivo;
		this.estado = estado;
	}

	public int getIdfotoPublicoDetalle() {
		return this.idfotoPublicoDetalle;
	}

	public void setIdfotoPublicoDetalle(int idfotoPublicoDetalle) {
		this.idfotoPublicoDetalle = idfotoPublicoDetalle;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	public String getUrlArchivo() {
		return this.urlArchivo;
	}

	public void setUrlArchivo(String urlArchivo) {
		this.urlArchivo = urlArchivo;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
