package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

/**
 * GestionAcademica generated by hbm2java
 */
public class GestionAcademica implements java.io.Serializable {

	private int idgestionAcademica;
	private Afiliado afiliado;
	private String nombreGestion;
	private String urlGestion;

	public GestionAcademica() {
	}

	public GestionAcademica(int idgestionAcademica, Afiliado afiliado) {
		this.idgestionAcademica = idgestionAcademica;
		this.afiliado = afiliado;
	}

	public GestionAcademica(int idgestionAcademica, Afiliado afiliado, String nombreGestion, String urlGestion) {
		this.idgestionAcademica = idgestionAcademica;
		this.afiliado = afiliado;
		this.nombreGestion = nombreGestion;
		this.urlGestion = urlGestion;
	}

	public int getIdgestionAcademica() {
		return this.idgestionAcademica;
	}

	public void setIdgestionAcademica(int idgestionAcademica) {
		this.idgestionAcademica = idgestionAcademica;
	}

	public Afiliado getAfiliado() {
		return this.afiliado;
	}

	public void setAfiliado(Afiliado afiliado) {
		this.afiliado = afiliado;
	}

	public String getNombreGestion() {
		return this.nombreGestion;
	}

	public void setNombreGestion(String nombreGestion) {
		this.nombreGestion = nombreGestion;
	}

	public String getUrlGestion() {
		return this.urlGestion;
	}

	public void setUrlGestion(String urlGestion) {
		this.urlGestion = urlGestion;
	}

}
