package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Opcion generated by hbm2java
 */
public class Opcion implements java.io.Serializable {

	private int idOpcion;
	private String opcionNombre;
	private String url;
	private Set rolOpcions = new HashSet(0);

	public Opcion() {
	}

	public Opcion(int idOpcion, String opcionNombre, String url) {
		this.idOpcion = idOpcion;
		this.opcionNombre = opcionNombre;
		this.url = url;
	}

	public Opcion(int idOpcion, String opcionNombre, String url, Set rolOpcions) {
		this.idOpcion = idOpcion;
		this.opcionNombre = opcionNombre;
		this.url = url;
		this.rolOpcions = rolOpcions;
	}

	public int getIdOpcion() {
		return this.idOpcion;
	}

	public void setIdOpcion(int idOpcion) {
		this.idOpcion = idOpcion;
	}

	public String getOpcionNombre() {
		return this.opcionNombre;
	}

	public void setOpcionNombre(String opcionNombre) {
		this.opcionNombre = opcionNombre;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Set getRolOpcions() {
		return this.rolOpcions;
	}

	public void setRolOpcions(Set rolOpcions) {
		this.rolOpcions = rolOpcions;
	}

}
