package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

/**
 * PersonaContacto generated by hbm2java
 */
public class PersonaContacto implements java.io.Serializable {

	private int idpersonaContacto;
	private String nombreCompleto;
	private String telefono;
	private String extension;
	private String celular;
	private String correoElectronico;

	public PersonaContacto() {
	}

	public PersonaContacto(int idpersonaContacto) {
		this.idpersonaContacto = idpersonaContacto;
	}

	public PersonaContacto(int idpersonaContacto, String nombreCompleto, String telefono, String extension,
			String celular, String correoElectronico) {
		this.idpersonaContacto = idpersonaContacto;
		this.nombreCompleto = nombreCompleto;
		this.telefono = telefono;
		this.extension = extension;
		this.celular = celular;
		this.correoElectronico = correoElectronico;
	}

	public int getIdpersonaContacto() {
		return this.idpersonaContacto;
	}

	public void setIdpersonaContacto(int idpersonaContacto) {
		this.idpersonaContacto = idpersonaContacto;
	}

	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

}
