package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Promocion generated by hbm2java
 */
public class Promocion implements java.io.Serializable {

	private int idpromociones;
	private Afiliado afiliado;
	private String nombre;
	private String descripcion;
	private String urlFoto;
	private String estado;
	private Date fechaInicio;
	private Date fechaFin;

	public Promocion() {
	}

	public Promocion(int idpromociones, Afiliado afiliado) {
		this.idpromociones = idpromociones;
		this.afiliado = afiliado;
	}

	public Promocion(int idpromociones, Afiliado afiliado, String nombre, String descripcion, String urlFoto,
			String estado, Date fechaInicio, Date fechaFin) {
		this.idpromociones = idpromociones;
		this.afiliado = afiliado;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.urlFoto = urlFoto;
		this.estado = estado;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
	}

	public int getIdpromociones() {
		return this.idpromociones;
	}

	public void setIdpromociones(int idpromociones) {
		this.idpromociones = idpromociones;
	}

	public Afiliado getAfiliado() {
		return this.afiliado;
	}

	public void setAfiliado(Afiliado afiliado) {
		this.afiliado = afiliado;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getUrlFoto() {
		return this.urlFoto;
	}

	public void setUrlFoto(String urlFoto) {
		this.urlFoto = urlFoto;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

}
