package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Publicacion generated by hbm2java
 */
public class Publicacion implements java.io.Serializable {

	private int idpublicacion;
	private TipoPublicacion tipoPublicacion;
	private Usuario usuario;
	private String nombrePublicacion;
	private Date fecha;
	private String estado;
	private String urlArchivo;

	public Publicacion() {
	}

	public Publicacion(int idpublicacion) {
		this.idpublicacion = idpublicacion;
	}

	public Publicacion(int idpublicacion, TipoPublicacion tipoPublicacion, Usuario usuario, String nombrePublicacion,
			Date fecha, String estado, String urlArchivo) {
		this.idpublicacion = idpublicacion;
		this.tipoPublicacion = tipoPublicacion;
		this.usuario = usuario;
		this.nombrePublicacion = nombrePublicacion;
		this.fecha = fecha;
		this.estado = estado;
		this.urlArchivo = urlArchivo;
	}

	public int getIdpublicacion() {
		return this.idpublicacion;
	}

	public void setIdpublicacion(int idpublicacion) {
		this.idpublicacion = idpublicacion;
	}

	public TipoPublicacion getTipoPublicacion() {
		return this.tipoPublicacion;
	}

	public void setTipoPublicacion(TipoPublicacion tipoPublicacion) {
		this.tipoPublicacion = tipoPublicacion;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getNombrePublicacion() {
		return this.nombrePublicacion;
	}

	public void setNombrePublicacion(String nombrePublicacion) {
		this.nombrePublicacion = nombrePublicacion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getUrlArchivo() {
		return this.urlArchivo;
	}

	public void setUrlArchivo(String urlArchivo) {
		this.urlArchivo = urlArchivo;
	}

}
