package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * RedSocial generated by hbm2java
 */
public class RedSocial implements java.io.Serializable {

	private int idredsocial;
	private String nombre;
	private Set redAfiliados = new HashSet(0);

	public RedSocial() {
	}

	public RedSocial(int idredsocial, String nombre) {
		this.idredsocial = idredsocial;
		this.nombre = nombre;
	}

	public RedSocial(int idredsocial, String nombre, Set redAfiliados) {
		this.idredsocial = idredsocial;
		this.nombre = nombre;
		this.redAfiliados = redAfiliados;
	}

	public int getIdredsocial() {
		return this.idredsocial;
	}

	public void setIdredsocial(int idredsocial) {
		this.idredsocial = idredsocial;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getRedAfiliados() {
		return this.redAfiliados;
	}

	public void setRedAfiliados(Set redAfiliados) {
		this.redAfiliados = redAfiliados;
	}

}
