package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

	private int idrol;
	private String rolNombre;
	private String descripcion;
	private Set rolOpcions = new HashSet(0);
	private Set usuarios = new HashSet(0);

	public Rol() {
	}

	public Rol(int idrol, String rolNombre) {
		this.idrol = idrol;
		this.rolNombre = rolNombre;
	}

	public Rol(int idrol, String rolNombre, String descripcion, Set rolOpcions, Set usuarios) {
		this.idrol = idrol;
		this.rolNombre = rolNombre;
		this.descripcion = descripcion;
		this.rolOpcions = rolOpcions;
		this.usuarios = usuarios;
	}

	public int getIdrol() {
		return this.idrol;
	}

	public void setIdrol(int idrol) {
		this.idrol = idrol;
	}

	public String getRolNombre() {
		return this.rolNombre;
	}

	public void setRolNombre(String rolNombre) {
		this.rolNombre = rolNombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getRolOpcions() {
		return this.rolOpcions;
	}

	public void setRolOpcions(Set rolOpcions) {
		this.rolOpcions = rolOpcions;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
