package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

/**
 * RolOpcion generated by hbm2java
 */
public class RolOpcion implements java.io.Serializable {

	private RolOpcionId id;
	private Opcion opcion;
	private Rol rol;

	public RolOpcion() {
	}

	public RolOpcion(RolOpcionId id, Opcion opcion, Rol rol) {
		this.id = id;
		this.opcion = opcion;
		this.rol = rol;
	}

	public RolOpcionId getId() {
		return this.id;
	}

	public void setId(RolOpcionId id) {
		this.id = id;
	}

	public Opcion getOpcion() {
		return this.opcion;
	}

	public void setOpcion(Opcion opcion) {
		this.opcion = opcion;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

}
