package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * SolicitudMentoria generated by hbm2java
 */
public class SolicitudMentoria implements java.io.Serializable {

	private int idsolicitudMentoria;
	private Carrera carrera;
	private Usuario usuarioByIdUsuario;
	private Usuario usuarioByIdUsuarioMentor;
	private String tematica;
	private Date fecha;
	private String estado;

	public SolicitudMentoria() {
	}

	public SolicitudMentoria(int idsolicitudMentoria, Carrera carrera, Usuario usuarioByIdUsuario) {
		this.idsolicitudMentoria = idsolicitudMentoria;
		this.carrera = carrera;
		this.usuarioByIdUsuario = usuarioByIdUsuario;
	}

	public SolicitudMentoria(int idsolicitudMentoria, Carrera carrera, Usuario usuarioByIdUsuario,
			Usuario usuarioByIdUsuarioMentor, String tematica, Date fecha, String estado) {
		this.idsolicitudMentoria = idsolicitudMentoria;
		this.carrera = carrera;
		this.usuarioByIdUsuario = usuarioByIdUsuario;
		this.usuarioByIdUsuarioMentor = usuarioByIdUsuarioMentor;
		this.tematica = tematica;
		this.fecha = fecha;
		this.estado = estado;
	}

	public int getIdsolicitudMentoria() {
		return this.idsolicitudMentoria;
	}

	public void setIdsolicitudMentoria(int idsolicitudMentoria) {
		this.idsolicitudMentoria = idsolicitudMentoria;
	}

	public Carrera getCarrera() {
		return this.carrera;
	}

	public void setCarrera(Carrera carrera) {
		this.carrera = carrera;
	}

	public Usuario getUsuarioByIdUsuario() {
		return this.usuarioByIdUsuario;
	}

	public void setUsuarioByIdUsuario(Usuario usuarioByIdUsuario) {
		this.usuarioByIdUsuario = usuarioByIdUsuario;
	}

	public Usuario getUsuarioByIdUsuarioMentor() {
		return this.usuarioByIdUsuarioMentor;
	}

	public void setUsuarioByIdUsuarioMentor(Usuario usuarioByIdUsuarioMentor) {
		this.usuarioByIdUsuarioMentor = usuarioByIdUsuarioMentor;
	}

	public String getTematica() {
		return this.tematica;
	}

	public void setTematica(String tematica) {
		this.tematica = tematica;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
