package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * SolicitudMentor generated by hbm2java
 */
public class SolicitudMentor implements java.io.Serializable {

	private int idsolicitudMentor;
	private Carrera carrera;
	private Usuario usuario;
	private String experiencia;
	private Date fecha;
	private String estado;
	private String turno;
	private String disponibilidad;

	public SolicitudMentor() {
	}

	public SolicitudMentor(int idsolicitudMentor, Carrera carrera, Usuario usuario) {
		this.idsolicitudMentor = idsolicitudMentor;
		this.carrera = carrera;
		this.usuario = usuario;
	}

	public SolicitudMentor(int idsolicitudMentor, Carrera carrera, Usuario usuario, String experiencia, Date fecha,
			String estado, String turno, String disponibilidad) {
		this.idsolicitudMentor = idsolicitudMentor;
		this.carrera = carrera;
		this.usuario = usuario;
		this.experiencia = experiencia;
		this.fecha = fecha;
		this.estado = estado;
		this.turno = turno;
		this.disponibilidad = disponibilidad;
	}

	public int getIdsolicitudMentor() {
		return this.idsolicitudMentor;
	}

	public void setIdsolicitudMentor(int idsolicitudMentor) {
		this.idsolicitudMentor = idsolicitudMentor;
	}

	public Carrera getCarrera() {
		return this.carrera;
	}

	public void setCarrera(Carrera carrera) {
		this.carrera = carrera;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getExperiencia() {
		return this.experiencia;
	}

	public void setExperiencia(String experiencia) {
		this.experiencia = experiencia;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getTurno() {
		return this.turno;
	}

	public void setTurno(String turno) {
		this.turno = turno;
	}

	public String getDisponibilidad() {
		return this.disponibilidad;
	}

	public void setDisponibilidad(String disponibilidad) {
		this.disponibilidad = disponibilidad;
	}

}
