package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TematicaPublicacion generated by hbm2java
 */
public class TematicaPublicacion implements java.io.Serializable {

	private int idTematicaPublicacion;
	private String tematicaPublicacion;
	private Set tipoPublicacions = new HashSet(0);

	public TematicaPublicacion() {
	}

	public TematicaPublicacion(int idTematicaPublicacion, String tematicaPublicacion) {
		this.idTematicaPublicacion = idTematicaPublicacion;
		this.tematicaPublicacion = tematicaPublicacion;
	}

	public TematicaPublicacion(int idTematicaPublicacion, String tematicaPublicacion, Set tipoPublicacions) {
		this.idTematicaPublicacion = idTematicaPublicacion;
		this.tematicaPublicacion = tematicaPublicacion;
		this.tipoPublicacions = tipoPublicacions;
	}

	public int getIdTematicaPublicacion() {
		return this.idTematicaPublicacion;
	}

	public void setIdTematicaPublicacion(int idTematicaPublicacion) {
		this.idTematicaPublicacion = idTematicaPublicacion;
	}

	public String getTematicaPublicacion() {
		return this.tematicaPublicacion;
	}

	public void setTematicaPublicacion(String tematicaPublicacion) {
		this.tematicaPublicacion = tematicaPublicacion;
	}

	public Set getTipoPublicacions() {
		return this.tipoPublicacions;
	}

	public void setTipoPublicacions(Set tipoPublicacions) {
		this.tipoPublicacions = tipoPublicacions;
	}

}
