package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

/**
 * UsuarioAfiliado generated by hbm2java
 */
public class UsuarioAfiliado implements java.io.Serializable {

	private int idusuarioAfiliado;
	private Afiliado afiliado;
	private String nombreUsuarioAfiliado;
	private String contraseniaAfiliado;
	private String estado;

	public UsuarioAfiliado() {
	}

	public UsuarioAfiliado(int idusuarioAfiliado, Afiliado afiliado, String nombreUsuarioAfiliado,
			String contraseniaAfiliado) {
		this.idusuarioAfiliado = idusuarioAfiliado;
		this.afiliado = afiliado;
		this.nombreUsuarioAfiliado = nombreUsuarioAfiliado;
		this.contraseniaAfiliado = contraseniaAfiliado;
	}

	public UsuarioAfiliado(int idusuarioAfiliado, Afiliado afiliado, String nombreUsuarioAfiliado,
			String contraseniaAfiliado, String estado) {
		this.idusuarioAfiliado = idusuarioAfiliado;
		this.afiliado = afiliado;
		this.nombreUsuarioAfiliado = nombreUsuarioAfiliado;
		this.contraseniaAfiliado = contraseniaAfiliado;
		this.estado = estado;
	}

	public int getIdusuarioAfiliado() {
		return this.idusuarioAfiliado;
	}

	public void setIdusuarioAfiliado(int idusuarioAfiliado) {
		this.idusuarioAfiliado = idusuarioAfiliado;
	}

	public Afiliado getAfiliado() {
		return this.afiliado;
	}

	public void setAfiliado(Afiliado afiliado) {
		this.afiliado = afiliado;
	}

	public String getNombreUsuarioAfiliado() {
		return this.nombreUsuarioAfiliado;
	}

	public void setNombreUsuarioAfiliado(String nombreUsuarioAfiliado) {
		this.nombreUsuarioAfiliado = nombreUsuarioAfiliado;
	}

	public String getContraseniaAfiliado() {
		return this.contraseniaAfiliado;
	}

	public void setContraseniaAfiliado(String contraseniaAfiliado) {
		this.contraseniaAfiliado = contraseniaAfiliado;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
