package entidades;
// Generated 11-26-2017 01:03:52 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private int idusuario;
	private Rol rol;
	private String identificacion;
	private String nombreUsuario;
	private String contrasenia;
	private String correo;
	private String codigoVerificacion;
	private String estatus;
	private String urlFoto;
	private Integer idCarrera;
	private String centroEstudio;
	private String celular;
	private String telefeono;
	private String direccion;
	private String objetivos;
	private Set solicitudMentors = new HashSet(0);
	private Set foroMentoriaDetalles = new HashSet(0);
	private Set evaluacionMentorsForIdUsuarioMentor = new HashSet(0);
	private Set valoracionPlans = new HashSet(0);
	private Set solicitudMentoriasForIdUsuario = new HashSet(0);
	private Set evaluacionMentoriadosForIdUsuarioMentoriado = new HashSet(0);
	private Set foroMentoriasForIdUsuarioMentor = new HashSet(0);
	private Set fotoPublicoDetalles = new HashSet(0);
	private Set foroMentoriasForIdUsuario = new HashSet(0);
	private Set evaluacionMentorsForIdUsuarioEvaluador = new HashSet(0);
	private Set foroPublicos = new HashSet(0);
	private Set publicacions = new HashSet(0);
	private Set solicitudMentoriasForIdUsuarioMentor = new HashSet(0);
	private Set articulos = new HashSet(0);
	private Set evaluacionMentoriadosForIdUsuarioMentor = new HashSet(0);

	public Usuario() {
	}

	public Usuario(int idusuario, Rol rol, String nombreUsuario, String contrasenia, String correo, String estatus) {
		this.idusuario = idusuario;
		this.rol = rol;
		this.nombreUsuario = nombreUsuario;
		this.contrasenia = contrasenia;
		this.correo = correo;
		this.estatus = estatus;
	}

	public Usuario(int idusuario, Rol rol, String identificacion, String nombreUsuario, String contrasenia,
			String correo, String codigoVerificacion, String estatus, String urlFoto, Integer idCarrera,
			String centroEstudio, String celular, String telefeono, String direccion, String objetivos,
			Set solicitudMentors, Set foroMentoriaDetalles, Set evaluacionMentorsForIdUsuarioMentor,
			Set valoracionPlans, Set solicitudMentoriasForIdUsuario, Set evaluacionMentoriadosForIdUsuarioMentoriado,
			Set foroMentoriasForIdUsuarioMentor, Set fotoPublicoDetalles, Set foroMentoriasForIdUsuario,
			Set evaluacionMentorsForIdUsuarioEvaluador, Set foroPublicos, Set publicacions,
			Set solicitudMentoriasForIdUsuarioMentor, Set articulos, Set evaluacionMentoriadosForIdUsuarioMentor) {
		this.idusuario = idusuario;
		this.rol = rol;
		this.identificacion = identificacion;
		this.nombreUsuario = nombreUsuario;
		this.contrasenia = contrasenia;
		this.correo = correo;
		this.codigoVerificacion = codigoVerificacion;
		this.estatus = estatus;
		this.urlFoto = urlFoto;
		this.idCarrera = idCarrera;
		this.centroEstudio = centroEstudio;
		this.celular = celular;
		this.telefeono = telefeono;
		this.direccion = direccion;
		this.objetivos = objetivos;
		this.solicitudMentors = solicitudMentors;
		this.foroMentoriaDetalles = foroMentoriaDetalles;
		this.evaluacionMentorsForIdUsuarioMentor = evaluacionMentorsForIdUsuarioMentor;
		this.valoracionPlans = valoracionPlans;
		this.solicitudMentoriasForIdUsuario = solicitudMentoriasForIdUsuario;
		this.evaluacionMentoriadosForIdUsuarioMentoriado = evaluacionMentoriadosForIdUsuarioMentoriado;
		this.foroMentoriasForIdUsuarioMentor = foroMentoriasForIdUsuarioMentor;
		this.fotoPublicoDetalles = fotoPublicoDetalles;
		this.foroMentoriasForIdUsuario = foroMentoriasForIdUsuario;
		this.evaluacionMentorsForIdUsuarioEvaluador = evaluacionMentorsForIdUsuarioEvaluador;
		this.foroPublicos = foroPublicos;
		this.publicacions = publicacions;
		this.solicitudMentoriasForIdUsuarioMentor = solicitudMentoriasForIdUsuarioMentor;
		this.articulos = articulos;
		this.evaluacionMentoriadosForIdUsuarioMentor = evaluacionMentoriadosForIdUsuarioMentor;
	}

	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	public String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public String getContrasenia() {
		return this.contrasenia;
	}

	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getCodigoVerificacion() {
		return this.codigoVerificacion;
	}

	public void setCodigoVerificacion(String codigoVerificacion) {
		this.codigoVerificacion = codigoVerificacion;
	}

	public String getEstatus() {
		return this.estatus;
	}

	public void setEstatus(String estatus) {
		this.estatus = estatus;
	}

	public String getUrlFoto() {
		return this.urlFoto;
	}

	public void setUrlFoto(String urlFoto) {
		this.urlFoto = urlFoto;
	}

	public Integer getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(Integer idCarrera) {
		this.idCarrera = idCarrera;
	}

	public String getCentroEstudio() {
		return this.centroEstudio;
	}

	public void setCentroEstudio(String centroEstudio) {
		this.centroEstudio = centroEstudio;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getTelefeono() {
		return this.telefeono;
	}

	public void setTelefeono(String telefeono) {
		this.telefeono = telefeono;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getObjetivos() {
		return this.objetivos;
	}

	public void setObjetivos(String objetivos) {
		this.objetivos = objetivos;
	}

	public Set getSolicitudMentors() {
		return this.solicitudMentors;
	}

	public void setSolicitudMentors(Set solicitudMentors) {
		this.solicitudMentors = solicitudMentors;
	}

	public Set getForoMentoriaDetalles() {
		return this.foroMentoriaDetalles;
	}

	public void setForoMentoriaDetalles(Set foroMentoriaDetalles) {
		this.foroMentoriaDetalles = foroMentoriaDetalles;
	}

	public Set getEvaluacionMentorsForIdUsuarioMentor() {
		return this.evaluacionMentorsForIdUsuarioMentor;
	}

	public void setEvaluacionMentorsForIdUsuarioMentor(Set evaluacionMentorsForIdUsuarioMentor) {
		this.evaluacionMentorsForIdUsuarioMentor = evaluacionMentorsForIdUsuarioMentor;
	}

	public Set getValoracionPlans() {
		return this.valoracionPlans;
	}

	public void setValoracionPlans(Set valoracionPlans) {
		this.valoracionPlans = valoracionPlans;
	}

	public Set getSolicitudMentoriasForIdUsuario() {
		return this.solicitudMentoriasForIdUsuario;
	}

	public void setSolicitudMentoriasForIdUsuario(Set solicitudMentoriasForIdUsuario) {
		this.solicitudMentoriasForIdUsuario = solicitudMentoriasForIdUsuario;
	}

	public Set getEvaluacionMentoriadosForIdUsuarioMentoriado() {
		return this.evaluacionMentoriadosForIdUsuarioMentoriado;
	}

	public void setEvaluacionMentoriadosForIdUsuarioMentoriado(Set evaluacionMentoriadosForIdUsuarioMentoriado) {
		this.evaluacionMentoriadosForIdUsuarioMentoriado = evaluacionMentoriadosForIdUsuarioMentoriado;
	}

	public Set getForoMentoriasForIdUsuarioMentor() {
		return this.foroMentoriasForIdUsuarioMentor;
	}

	public void setForoMentoriasForIdUsuarioMentor(Set foroMentoriasForIdUsuarioMentor) {
		this.foroMentoriasForIdUsuarioMentor = foroMentoriasForIdUsuarioMentor;
	}

	public Set getFotoPublicoDetalles() {
		return this.fotoPublicoDetalles;
	}

	public void setFotoPublicoDetalles(Set fotoPublicoDetalles) {
		this.fotoPublicoDetalles = fotoPublicoDetalles;
	}

	public Set getForoMentoriasForIdUsuario() {
		return this.foroMentoriasForIdUsuario;
	}

	public void setForoMentoriasForIdUsuario(Set foroMentoriasForIdUsuario) {
		this.foroMentoriasForIdUsuario = foroMentoriasForIdUsuario;
	}

	public Set getEvaluacionMentorsForIdUsuarioEvaluador() {
		return this.evaluacionMentorsForIdUsuarioEvaluador;
	}

	public void setEvaluacionMentorsForIdUsuarioEvaluador(Set evaluacionMentorsForIdUsuarioEvaluador) {
		this.evaluacionMentorsForIdUsuarioEvaluador = evaluacionMentorsForIdUsuarioEvaluador;
	}

	public Set getForoPublicos() {
		return this.foroPublicos;
	}

	public void setForoPublicos(Set foroPublicos) {
		this.foroPublicos = foroPublicos;
	}

	public Set getPublicacions() {
		return this.publicacions;
	}

	public void setPublicacions(Set publicacions) {
		this.publicacions = publicacions;
	}

	public Set getSolicitudMentoriasForIdUsuarioMentor() {
		return this.solicitudMentoriasForIdUsuarioMentor;
	}

	public void setSolicitudMentoriasForIdUsuarioMentor(Set solicitudMentoriasForIdUsuarioMentor) {
		this.solicitudMentoriasForIdUsuarioMentor = solicitudMentoriasForIdUsuarioMentor;
	}

	public Set getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Set articulos) {
		this.articulos = articulos;
	}

	public Set getEvaluacionMentoriadosForIdUsuarioMentor() {
		return this.evaluacionMentoriadosForIdUsuarioMentor;
	}

	public void setEvaluacionMentoriadosForIdUsuarioMentor(Set evaluacionMentoriadosForIdUsuarioMentor) {
		this.evaluacionMentoriadosForIdUsuarioMentor = evaluacionMentoriadosForIdUsuarioMentor;
	}

}
